#!/bin/bash

# Shortcuts

# alias e="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
alias e="atom"
alias dev="cd ~/Development/"
alias ..="cd .."
alias o="open"
alias oo="open ."
alias b="cd -"
alias t="tree"
alias mo="makeopen"
alias lib="cd ~/Library/ && open ."
alias del="saferm"
alias cb="copytoclipboard"

# Reload dotfiles
alias src="source ~/.bash_profile"

# Apache
alias apache="sudo apachectl"
alias hosts="e /etc/hosts"
alias vhosts="e /private/etc/apache2/extra/httpd-vhosts.conf"

# Processes
alias pfind="ps aux | grep"
alias pmem="top -o vsize"
alias pcpu="top -o cpu"
alias pkill="kill -9 "

# List all files colorized in long format
alias l="ls -Glh"
# Show hidden
alias la="ls -Glha"
# Only dirs
alias ld='ls -lh | grep "^d"'

# Always use color output for `ls`
alias ls="command ls -G"

# Enable aliases to be sudo’ed
alias sudo='sudo '

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# View HTTP traffic
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# File size
alias size="stat -f \"%z bytes\""

# Show/hide hidden files in Finder
alias show="defaults write com.apple.finder AppleShowAllFiles YES && killall Finder"
alias hide="defaults write com.apple.finder AppleShowAllFiles NO && killall Finder"
