#!/bin/bash

alias bd="bashdots"

function bashdots() {
		
		# CD to Bashdots if no args
		if [ "$1" == "" ]; then
			cd "$BASHDOTS_DIR"

		# Update flag
		elif [ "$1" == "--update" -o "$1" == "-u" ]; then
			echo "Updating BashDots..."
			git pull "$BASHDOTS_DIR"
			source "~/.bash_profile"
			echo "Done"

		# Show help flag
		elif [ "$1" == "--help" -o "$1" == "-h" ]; then
			echo "BashDots help in progress"
		
		# Lastly show usage if arg not recognised
		else
			echo "BashDots usage in progress"	

		fi
	}