#!/bin/bash

# Colors
BLACK='\e[0;30m'
RED='\e[0;31m'
GREEN='\e[0;32m'
YELLOW='\e[0;33m'
BLUE='\e[0;34m'
PURPLE='\e[0;35m'
CYAN='\e[0;36m'
WHITE='\e[0;37m'
# Bold
bBLACK='\e[1;30m'
bRED='\e[1;31m'
bGREEN='\e[1;32m'
bYELLOW='\e[1;33m'
bBLUE='\e[1;34m'
bPURPLE='\e[1;35m'
bCYAN='\e[1;36m'
bWHITE='\e[1;37m'
# Text Reset
RESET='\e[0m'

# Bash prompt
PS1="\n\[$bBLACK\]\w\n\[$bGREEN\]>\[$RESET\] "