#!/bin/bash

# Dotfiles

alias d="cd ~/.bashdots/"
alias de="subl ~/.bashdots/bash_*"

# Shortcuts

alias subl="/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl"
alias e="subl"
alias dev="cd ~/Development/"
alias mamp="cd /Applications/MAMP/htdocs/"
alias ..="cd .."
alias o="open"
alias oo="open ."

# Git
alias g="git status"
alias gi="git init"
alias ga="git add"
alias gc="git commit -m"
alias gb="git branch"
alias gp="git pull"
alias gpo="git push origin"

# Processes
alias pfind="ps aux | grep"
alias pmem="top -o vsize"
alias pcpu="top -o cpu"
alias pkill="kill -9 "

# List all files colorized in long format
alias l="ls -Gl"
# Show hidden
alias la="ls -Gla"
# Only dirs
alias ld='ls -l | grep "^d"'

# Always use color output for `ls`
alias ls="command ls -G"

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Get OS X Software Updates, update Homebrew itself, and upgrade installed Homebrew packages
alias update='sudo softwareupdate -i -a; brew update; brew upgrade'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"

# Enhanced WHOIS lookups
alias whois="whois -h whois-servers.net"

# View HTTP traffic
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# File size
alias size="stat -f \"%z bytes\""

# Empty the Trash on all mounted volumes and the main HDD
# Also, clear Apple’s System Logs to improve shell startup speed
alias clean="sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl"

# Show/hide hidden files in Finder
alias show="defaults write com.apple.Finder AppleShowAllFiles -bool true && killall Finder"
alias hide="defaults write com.apple.Finder AppleShowAllFiles -bool false && killall Finder"

# Kill volume
alias mute="osascript -e 'set volume 0'"