#!/bin/bash

# Aliases
alias g="git status"
alias gi="git init"
alias ga="git add"
alias gc="bd_git_commit"
alias gb="git branch"
alias gp="bd_git_push"
alias gpl="git pull"

# Functions
function bd_git_commit() {
	git commit -m "$1"
}

# Git push
function bd_git_push() {
	if [ -n "$1" ]; then # Check if not master
		git push origin $1
	else # Default master
		git push origin master
	fi
}

# Use Git colored diff when available
hash git &>/dev/null
if [ $? -eq 0 ]; then
	function diff() {
		git diff --no-index --color-words "$@"
	}
fi