#!/bin/bash

# ====== Aliases ======

alias g="git status"
alias gl="git log"
alias gi="git init"
alias ga="bd_git_add"
alias gc="git commit -v -m"
alias gm="git merge"
alias gb="git branch"
alias gco="git checkout"
alias gp="bd_git_push"
alias gpl="git pull"
alias gr="git reset HEAD"

# ====== Functions ======

# Git push
function bd_git_push() {
	if [ "$1" ]; then # Check if not master
		git push origin $1
	else # Default master
		git push origin master
	fi
}

# Git add
function bd_git_add() {
	if [ "$1" ]; then # Check if argument passed
		git add $1
	else # Default to -A
		git add -A
	fi
}

# Use Git colored diff when available
hash git &>/dev/null
if [ $? -eq 0 ]; then
	function diff() {
		git diff --no-index --color-words "$@"
	}
fi