#!/bin/bash

# ====== Aliases ======

alias g="git status"
alias gl="git log --graph --color --pretty=format:'%x1b[31m%h%x1b[0m%x20- %s %x1b[32m%d'"
alias gi="git init"
alias ga="bd_git_add"
alias gc="git commit -v -m"
alias gm="git merge"
alias gb="git branch"
alias gco="git checkout"
alias gp="bd_git_push"
alias gpl="git pull"
alias gr="git reset HEAD"
alias gamend="git commit --amend -m"

# ====== Functions ======

# Git push
function bd_git_push() {
	if [ "$1" ]; then # Check if not master
		git push origin $1
	else # Default master
		git push origin master
	fi
}

# Git add
function bd_git_add() {
	if [ "$1" ]; then # Check if argument passed
		git add $1
	else # Default to -A
		git add -A
	fi
}

# Check git dirty
function git_dirty() {
	[[ $(git status 2> /dev/null | tail -n1) != "nothing to commit (working directory clean)" ]] && echo "*"
}

# Return current branch
function git_branch() {
	git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

# Use Git colored diff when available
hash git &>/dev/null
if [ $? -eq 0 ]; then
	function diff() {
		git diff --no-index --color-words "$@"
	}
fi